"""
Code generator for the generalized block syntax.

The generator simply serializes the parsed AST and feeds it into the block
runtime helper.
"""

from __future__ import annotations

from textwrap import dedent
from typing import Any, Dict, Optional


class BlockCodeGenerator:
    """Emit Python code for the block-based LevLang syntax."""

    def __init__(self, ast: Optional[Dict[str, Any]]):
        self.ast = ast or {}

    def generate(self) -> str:
        blocks = repr(self.ast.get("blocks", {}))
        globals_data = repr(self.ast.get("globals", {}))
        ui_data = repr(self.ast.get("ui", []))

        script = dedent(
            f"""
            # Generated by LevLang BlockCodeGenerator
            # NOTE: Edits to this file will be overwritten on the next build.

            from levlang.runtime.simple_runtime import run_block_game


            BLOCK_DATA = {{
                "blocks": {blocks},
                "globals": {globals_data},
                "ui": {ui_data},
            }}


            def main():
                run_block_game(BLOCK_DATA)


            if __name__ == "__main__":
                main()
            """
        ).lstrip()

        return script + "\n"

