"""
Runtime-backed code generator for the LevLang v3 component syntax.

Generated files stay tiny: we simply embed the parsed AST (components,
entities, and game config) and hand it to `levlang.runtime.simple_runtime`
which owns the pygame loop, entities, UI helpers, etc.
"""

from __future__ import annotations

import json
from textwrap import dedent
from typing import Any, Dict


class SimpleCodeGenerator:
    """Generate a lightweight launcher that feeds data into the runtime."""

    def __init__(self, ast: Dict[str, Any]):
        self.ast = ast or {}
        self.components = self.ast.get("components", {})
        self.entities = self.ast.get("entities", {})
        self.game = self.ast.get("game", {})

    def generate(self) -> str:
        """Return a python script that invokes the shared runtime."""
        # Validate that AST data is serializable
        try:
            json.dumps(self.components)
            json.dumps(self.entities)
            json.dumps(self.game)
        except (TypeError, ValueError) as e:
            raise ValueError(f"AST data is not serializable: {e}") from e
        
        script = dedent(
            f"""
            # Generated by LevLang SimpleCodeGenerator
            # NOTE: This file is auto-generated. Manual edits will be lost.

            from levlang.runtime.simple_runtime import run_component_game


            COMPONENTS = {repr(self.components)}
            ENTITY_DEFS = {repr(self.entities)}
            GAME_CONFIG = {repr(self.game)}


            def main():
                run_component_game(COMPONENTS, ENTITY_DEFS, GAME_CONFIG)


            if __name__ == "__main__":
                main()
            """
        ).lstrip()
        return script + "\n"
