# Generated by LevLang BlockCodeGenerator
# NOTE: Edits to this file will be overwritten on the next build.

from levlang.runtime.simple_runtime import run_block_game

BLOCK_DATA = {
    "blocks": {'game': {'title': 'Highway Dodge'}, 'player': {'shape': 'rectangle', 'color': 'blue', 'size': '40x70', 'speed': 8, 'movement': 'wasd_arrows'}, 'road': {'lanes': 4, 'scrolling': True}, 'enemy': {'shape': 'rectangle', 'color': 'random', 'size': '40x70', 'spawn': 'random_lane', 'speed': 'rand(5, 7)', 'move': 'down', 'offscreen': 'destroy, score+1', 'collide': 'gameover'}, 'gameover': {'_lines': ['CRASHED!', 'Final Score: {score}', 'Press SPACE to try again'], 'on_key(SPACE)': 'restart()'}},
    "globals": {'spawn_rate': '1.5sec', 'start': True},
    "ui": [[{'text': 'Score: {score}', 'anchor': 'topleft', 'offset': (0, 0)}]],
}


def main():
    run_block_game(BLOCK_DATA)


if __name__ == "__main__":
    main()

