"""Unit tests for the code generator."""

import pytest
from levlang.lexer import Lexer
from levlang.parser import Parser
from levlang.semantic import SemanticAnalyzer
from levlang.codegen import CodeGenerator


class TestCodeGeneratorBasics:
    """Test basic code generator functionality."""
    
    def test_empty_program(self):
        """Test generating code from empty program."""
        source = ""
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Should at least have imports
        assert "import pygame" in code
        assert "import sys" in code
    
    def test_header_generation(self):
        """Test that file header is generated."""
        source = ""
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        assert "Generated by GameLang Transpiler" in code


class TestSpriteGeneration:
    """Test sprite class generation."""
    
    def test_simple_sprite(self):
        """Test generating a simple sprite class."""
        source = """
        sprite Player {
            x = 100
            y = 200
            speed = 5
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check class definition
        assert "class Player(pygame.sprite.Sprite):" in code
        assert "def __init__(self):" in code
        assert "super().__init__()" in code
        
        # Check properties
        assert "self.x = 100" in code
        assert "self.y = 200" in code
        assert "self.speed = 5" in code
    
    def test_sprite_with_image(self):
        """Test generating sprite with image property."""
        source = """
        sprite Player {
            image = "player.png"
            x = 100
            y = 200
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check image loading
        assert "pygame.image.load" in code
        assert "self.rect = self.image.get_rect()" in code
        assert "self.rect.center = (self.x, self.y)" in code
    
    def test_sprite_with_event_handler(self):
        """Test generating sprite with event handler."""
        source = """
        sprite Player {
            x = 100
            
            on keydown(key) {
                if key == "LEFT" {
                    x = x - 5
                }
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check event handler method
        assert "def handle_keydown(self, key):" in code
        assert 'if (key == "LEFT"):' in code


class TestGameInitialization:
    """Test game initialization code generation."""
    
    def test_game_with_properties(self):
        """Test generating game initialization with properties."""
        source = """
        game MyGame {
            title = "Test Game"
            width = 800
            height = 600
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check pygame initialization
        assert "def main():" in code
        assert "pygame.init()" in code
        
        # Check display setup
        assert "pygame.display.set_mode((800, 600))" in code
        assert 'pygame.display.set_caption("Test Game")' in code
        
        # Check clock
        assert "clock = pygame.time.Clock()" in code
    
    def test_default_game_config(self):
        """Test generating game with default configuration."""
        source = """
        sprite Player {
            x = 100
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Should still have main function with defaults
        assert "def main():" in code
        assert "pygame.init()" in code


class TestGameLoop:
    """Test game loop generation."""
    
    def test_game_loop_structure(self):
        """Test that game loop has correct structure."""
        source = """
        sprite Player {
            x = 100
        }
        
        scene Main {
            update {
                x = x + 1
            }
            
            draw {
                screen.fill((0, 0, 0))
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check game loop structure
        assert "running = True" in code
        assert "while running:" in code
        assert "for event in pygame.event.get():" in code
        assert "if event.type == pygame.QUIT:" in code
        assert "running = False" in code
        
        # Check display update
        assert "pygame.display.flip()" in code
        assert "clock.tick(60)" in code
        
        # Check pygame quit
        assert "pygame.quit()" in code
    
    def test_sprite_instantiation(self):
        """Test that sprites are instantiated in main."""
        source = """
        sprite Player {
            x = 100
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check sprite instantiation
        assert "player = Player()" in code
    
    def test_entry_point(self):
        """Test that entry point is generated."""
        source = """
        sprite Player {
            x = 100
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check entry point
        assert "if __name__ == '__main__':" in code
        assert "main()" in code


class TestEventHandlerGeneration:
    """Test event handler code generation."""
    
    def test_keydown_event(self):
        """Test generating keydown event handler."""
        source = """
        sprite Player {
            on keydown(key) {
                x = x - 5
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check event handling in game loop
        assert "if event.type == pygame.KEYDOWN:" in code
        assert "key = pygame.key.name(event.key).upper()" in code
        assert "player.handle_keydown(key)" in code


class TestExpressionGeneration:
    """Test expression code generation."""
    
    def test_literal_expressions(self):
        """Test generating literal expressions."""
        source = """
        sprite Player {
            x = 100
            name = "Player"
            active = true
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check literals
        assert "self.x = 100" in code
        assert 'self.name = "Player"' in code
        assert "self.active = True" in code
    
    def test_binary_operations(self):
        """Test generating binary operations."""
        source = """
        sprite Player {
            on keydown(key) {
                x = x + 5
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check binary operation
        assert "(x + 5)" in code or "x + 5" in code


class TestStatementGeneration:
    """Test statement code generation."""
    
    def test_if_statement(self):
        """Test generating if statements."""
        source = """
        sprite Player {
            on keydown(key) {
                if key == "LEFT" {
                    x = x - 5
                }
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check if statement
        assert "if" in code
        assert "==" in code
    
    def test_while_statement(self):
        """Test generating while statements."""
        source = """
        scene Main {
            update {
                while x < 100 {
                    x = x + 1
                }
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Check while statement
        assert "while" in code


class TestCodeValidity:
    """Test that generated code is valid Python."""
    
    def test_generated_code_compiles(self):
        """Test that generated code can be compiled."""
        source = """
        game MyGame {
            title = "Test"
            width = 800
            height = 600
        }
        
        sprite Player {
            x = 100
            y = 200
            speed = 5
        }
        
        scene Main {
            update {
                x = x + 1
            }
            
            draw {
                screen.fill((0, 0, 0))
            }
        }
        """
        lexer = Lexer(source, "test.lvl")
        tokens = lexer.tokenize()
        parser = Parser(tokens)
        ast = parser.parse()
        
        generator = CodeGenerator(ast)
        code = generator.generate()
        
        # Try to compile the generated code
        try:
            compile(code, '<generated>', 'exec')
            compiled = True
        except SyntaxError:
            compiled = False
        
        assert compiled, "Generated code should be valid Python"
