# Generated by LevLang Transpiler
# This file was automatically generated from LevLang source code

import os
os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = '1'

import pygame
import random
import sys

# Initialize Pygame
pygame.init()

# Constants
WIDTH, HEIGHT = 800, 600
FPS = 60
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 100, 255)
CYAN = (0, 255, 255)
PURPLE = (128, 0, 128)
ORANGE = (255, 165, 0)
GRAY = (100, 100, 100)
YELLOW = (255, 255, 0)

# Create display
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Road Dodger")

# Set custom window icon
try:
    icon = pygame.image.load("levelanglogo.png")
    pygame.display.set_icon(icon)
except (pygame.error, FileNotFoundError, OSError):
    # If icon loading fails, create a simple fallback icon
    try:
        icon = pygame.Surface((32, 32))
        icon.fill((0, 100, 255))
        pygame.draw.rect(icon, (255, 255, 255), (8, 8, 16, 16))
        pygame.display.set_icon(icon)
    except pygame.error:
        pass

clock = pygame.time.Clock()

class Player:
    def __init__(self):
        self.width = 40
        self.height = 50
        self.x = WIDTH // 2 - self.width // 2
        self.y = HEIGHT - self.height - 20
        self.speed = 8
        self.score = 0
        self.shape = 'triangle'
        
    def move(self, keys):
        if (keys[pygame.K_LEFT] or keys[pygame.K_a]) and self.x > 150:
            self.x -= self.speed
        if (keys[pygame.K_RIGHT] or keys[pygame.K_d]) and self.x < WIDTH - 150 - self.width:
            self.x += self.speed
        if (keys[pygame.K_UP] or keys[pygame.K_w]) and self.y > 0:
            self.y -= self.speed
        if (keys[pygame.K_DOWN] or keys[pygame.K_s]) and self.y < HEIGHT - self.height:
            self.y += self.speed
    
    def draw(self, surface):
        points = [(self.x + self.width//2, self.y), (self.x, self.y + self.height), (self.x + self.width, self.y + self.height)]
        pygame.draw.polygon(surface, CYAN, points)

class ObstacleCar:
    def __init__(self):
        self.width = 35
        self.height = 35
        self.x = random.choice([200, 300, 400, 500])
        self.y = -100
        self.speed = random.randint(3, 7)
        self.color = random.choice([RED, GREEN, YELLOW, (255, 165, 0)])
        self.shape = 'circle'
        
    def move(self):
        self.y += self.speed
    
    def draw(self, surface):
        pygame.draw.circle(surface, self.color, (int(self.x + self.width//2), int(self.y + self.height//2)), self.width//2)
    
    def is_off_screen(self):
        return self.y > HEIGHT

class Road:
    def __init__(self):
        self.y1 = 0
        self.y2 = -HEIGHT
        self.line_speed = 5
        
    def draw(self, surface):
        # Road background
        pygame.draw.rect(surface, GRAY, (150, 0, WIDTH - 300, HEIGHT))
        # Road edges
        pygame.draw.rect(surface, WHITE, (150, 0, 10, HEIGHT))
        pygame.draw.rect(surface, WHITE, (WIDTH - 160, 0, 10, HEIGHT))
        
        # Lane dividers (4 lanes)
        for i in range(3):
            x = 250 + i * 100
            # Moving dashed lines
            for y in range(int(self.y1), HEIGHT, 40):
                pygame.draw.rect(surface, WHITE, (x, y, 5, 20))
    
    def update(self):
        self.y1 += self.line_speed
        if self.y1 >= 40:
            self.y1 = 0

def check_collision(player, obstacle):
    px, py = player.x, player.y
    ox, oy = obstacle.x, obstacle.y
    
    if (px < ox + obstacle.width and
        px + player.width > ox and
        py < oy + obstacle.height and
        py + player.height > oy):
        return True
    return False

def draw_text(surface, text, size, x, y, color=WHITE):
    font = pygame.font.Font(None, size)
    text_surface = font.render(text, True, color)
    text_rect = text_surface.get_rect()
    text_rect.midtop = (x, y)
    surface.blit(text_surface, text_rect)

def game_over_screen(score):
    screen.fill(BLACK)
    draw_text(screen, "GAME OVER!", 64, WIDTH // 2, HEIGHT // 4, RED)
    draw_text(screen, "Final Score: " + str(score), 40, WIDTH // 2, HEIGHT // 2)
    draw_text(screen, "Press SPACE to Play Again", 30, WIDTH // 2, HEIGHT * 3 // 4)
    pygame.display.flip()
    
    waiting = True
    while waiting:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return False
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_SPACE:
                    return True
                if event.key == pygame.K_ESCAPE:
                    return False
    return False

def main():
    running = True
    
    while running:
        # Game variables
        player = Player()
        obstacles = []
        road = Road()
        game_active = True
        spawn_timer = 0
        difficulty = 60
        
        # Game loop
        while game_active:
            clock.tick(FPS)
            
            # Event handling
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                if event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_ESCAPE:
                        pygame.quit()
                        sys.exit()
            
            # Get keys
            keys = pygame.key.get_pressed()
            player.move(keys)
            
            # Spawn obstacles
            spawn_timer += 1
            if spawn_timer > difficulty:
                obstacles.append(ObstacleCar())
                spawn_timer = 0
                # Increase difficulty over time
                if difficulty > 30:
                    difficulty -= 0.5
            
            # Update obstacles
            for obstacle in obstacles[:]:
                obstacle.move()
                if obstacle.is_off_screen():
                    obstacles.remove(obstacle)
                    player.score += 10
                elif check_collision(player, obstacle):
                    game_active = False
            
            # Update road
            road.update()
            
            # Draw everything
            screen.fill(GREEN)
            road.draw(screen)
            player.draw(screen)
            for obstacle in obstacles:
                obstacle.draw(screen)
            
            # Draw UI
            draw_text(screen, "Road Dodger - Dodge Cars!", 36, 80, 10)
            draw_text(screen, "Score: " + str(player.score) + "", 24, WIDTH - 100, 10)
            
            pygame.display.flip()
        
        # Game over
        running = game_over_screen(player.score)
    
    pygame.quit()

if __name__ == "__main__":
    main()